GET https://api.github.com/orgs/microsoft/events


###
GET https://api.github.com/organizations/6154722/events?page=10
ETag: "9e6892a4eba48e57a40ae27909604bf7"

###
GET https://api.github.com/repos/microsoft/dotnet/commits
If-None-Match: "ec0dee000784d029214a10d5021fb39f"

###
GET https://api.github.com/repos/microsoft/dotnet/commits?page=2
If-None-Match: "007c4f4d7df5af11d37a2518b217ba78"
